# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "ECEn 625: Compilation Strategies for High-Performance Systems"
class_name: Computer Networking
class_number: ECEn 625
email: jgoeders@byu.edu
description: >-
  Class website for BYU's ECEn 625: Compilation Strategies for High-Performance Systems.
baseurl: "/625" # the subpath of your site, e.g. /blog

# # url: "https://ecenetworking.byu.edu" # the base hostname & protocol for your site, e.g. http://example.com
# permalink: pretty

# # Build settings
# markdown: kramdown
# # plugins:
# #   - jekyll-feed

# github:
#   url: https://github.com/NET-BYU/networking-course
#   branch: master

# collections:
#   labs:
#     output: true
#     permalink: /:collection/:name/
#     sort_by: number
#   homeworks:
#     output: true
#     permalink: /:collection/:name/
#     sort_by: chapter
#   pages:
#     output: true
#     permalink: /:name/
#     order:
#       - overview.md
#       - goals.md
#       # - resources.md
#       # - coding_standard.md
#       - lab_setup.md

# # Exclude from processing.
# # The following items will not be processed, by default. Create a custom list
# # to override the default setting.
# exclude:
#   - icon.ai
#   - Dockerfile
#   - Makefile
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
