name: Check links

on: [push, pull_request]

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check links
        run: |
          sudo apt-get install -y ruby-full build-essential zlib1g-dev
          sudo gem install bundler
          bundle install
          make check_links
        
